### PR TITLE
bump middleware to latest stables

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @fommil,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Typesafe Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by fommil** [comment]
this PR is too small to fall under the requirements of any CLA.

**Comment by fommil** [comment]
Close?

**Comment by eed3si9n** [comment]
oops. sorry I think it just slipped out of my attention. I didn't mean to ignore it.

**Pull request merged**
