### PR TITLE
Run CI on Windows

### PR DESCRIPTION
**Pull request by nightscape**
I'm noticing an error on Windows for `2.0.0-RC1` which was not there under `1.2.0` (will create a ticket for that).
As a first step for fixing this it would be good if the CI discovered and exposed the error.
I'm hoping that adding Windows to the build matrix already does so.

### CODE REVIEW

**Comment by nightscape** [comment]
@eed3si9n this PR would be ready to squash-merge from my side. It exposes the Windows bug in https://github.com/sbt/sbt-assembly/issues/472
What is not clear is if the Windows CI build would succeed if the bug was fixed.
In order to test that, one would probably have to run the Windows CI against version `1.2.0` which is not affected by the bug.
Any recommendations on how to proceed here?

**Comment by eed3si9n** [comment]
> Any recommendations on how to proceed here?

I just created a branch called 1.x out of 1.2.0 - https://github.com/sbt/sbt-assembly/tree/1.x
You could send another PR if you would like against it.

**Comment by nightscape** [comment]
Done in https://github.com/sbt/sbt-assembly/pull/473
Once that PR builds correctly on Windows, we can move on with this one here.

**Comment by fnqista** [comment]
Hey man,

I just wanna kindly follow up on a new release for sbt-assembly. Thanks in
advance

**Pull request merged**
