### PR TITLE
Manifest merge strategy

### PR DESCRIPTION
**Pull request by catap**

### CODE REVIEW

**Comment by eed3si9n** [comment]
Thanks for the contribution.

**Comment by purefn** [comment]
I recently upgraded my version sbt-assembly and ran into this unexpected behavior. I'd much rather duplicate mailcaps would either use `deduplicate` or `filterDistinctLines` as a default behavior. `discard`  as default has caused us to introduce a rather embarrassing bug.

**Comment by eed3si9n** [comment]
@purefn Sorry about that. I should've escalated this as a defect.

**Comment by eed3si9n** [comment]
I wonder if discarding `mimetypes.default` causes similar unexpected bugs.

**Comment by eed3si9n** [comment]
Added #190.

**Pull request merged**
