### PR TITLE
Allow shading to work in presence of unmanaged jars

### PR DESCRIPTION
**Pull request by philwills**
Previously shading threw a `None.get` exception if there were any unmanaged jars within the project, even if the shading was only requested on managed jars.

### CODE REVIEW

**Comment by philwills** [comment]
I'm not familiar with scripted, so apologies if I've done this in an clumsy manner.

**Comment by eed3si9n** [comment]
LGTM

**Comment by matt-martin** [comment]
@philwills not sure if this is the best place to ask, but can you elaborate on how one goes about specifying that only managed jars should be included (i.e. "even if the shading was only requested on managed jars")?

**Comment by philwills** [comment]
@matt-martin I just meant that there weren't any `ShadeRule`, as in https://github.com/philwills/sbt-assembly/blob/db68c4982892057237b3114e7734431615fec192/src/sbt-test/shading/unmanagedjars/build.sbt#L7 that applied to any class in the unmanaged jars.

**Pull request merged**
